In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'Name': ['john','Anna','peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df = pd.DataFrame(data)

In [18]:
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
data_list = [
    ['john',28,'New York',65000],
    ['Anna',30,'Paris',70000],
    ['Peter',34,'Berlin',87000],
    ['Linda',43,'London',98000]
]

columns=['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)

In [20]:
df2[['Name','City']]

    Name      City
0   john  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [22]:
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df.loc[[2,3],["Name","Age"]]

    Name  Age
2  peter   29
3  Linda   42

In [25]:
df[df["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000